version: "3"

services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - /home/${USER}/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - pgnetwork
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 4G
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@hostname.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - pgdb
    networks:
      - pgnetwork
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    networks:
      - pgnetwork
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  pgnetwork:
