version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/${USER}/docker/volumes/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "username@hostname.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:

