version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/iury/docker/volumes/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-network

  postgres1:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - /home/iury/docker/volumes/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-network

  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "username@hostname.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    volumes:
      - /home/iury/docker/volumes/postgres:/var/lib/pgadmin
    networks:
      - postgres-network

networks:
  postgres-network:

